# Generated by Django 3.1.5 on 2021-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
