# Generated by Django 4.0.5 on 2022-06-08 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_blog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 8, 22, 3, 11, 221196), null=True),
        ),
    ]
