# Generated by Django 3.1.5 on 2021-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
