# Generated by Django 3.1.5 on 2021-03-14 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtxtedit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
